### ISSUE TITLE
FIX examples and download data function

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sample-project#5]
In the examples I only download the data in one example ([here](https://11-227373822-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/auto_gallery-1/plot_1_download_data.html#sphx-glr-auto-gallery-1-plot-1-download-data-py)), assuming it will be the first one executed when building the doc, and in the second example I assume the data has been downloaded ([here](https://11-227373822-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/auto_gallery-1/plot_2_data2.html)) and only get the path to the data.

I think we can't assume that the examples will be executed in a specific order (can we?) so I will amend so both examples use the download function and amend the download function to find the correct data dir and return the data (currently just returns path to data).

**Comment by larsoner** [comment]
> I think we can't assume that the examples will be executed in a specific order (can we?) so I will amend so both examples use the download function 

Sounds good

> dir and return the data (currently just returns path to data)

In MNE at least we always return the path (`str`), not an object loaded by our library based on the contents of the path. It's a bit more general so that you can have datasets with multiple files and so forth. And sometimes when constructing objects you might want to provide options, etc.
