### ISSUE TITLE
Use github actions?

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sample-project#7]
Should we use github actions to render the sample project? It would have the benefit to be very easy to set up by end users.

**Comment by lucyleeow** [comment]
This: https://github.com/marketplace/actions/sphinx-build ?

It's being rendered by CircleCi atm - is github actions preferable? I'm not familiar with it.

**Comment by larsoner** [comment]
We could render it both ways, that way users can choose which deployment option they prefer.

Azure could also be used for example, and it's probably at least as easy as CircleCI. And AppVeyor also has some artifacts support. But we can add these as people become motivated to do so.

**Comment by choldgraf** [comment]
I am fine with providing a github actions pathway for people*, I've heard a lot of folks say it's a helpful way to get started with non-trivial actions, and anyway it is now one of the standard ways to do CI/CD so we should mention it.



*...I must admit that my biggest concern is using a single microsoft-owned vertical stack for everything open source, but apparently everybody thinks that Microsoft is now a friendly open source company instead of a giant monopolist trying to control the open source stack ;-)

**Comment by GaelVaroquaux** [comment]
I think that we should demo the github action thing: it is easier to set
up.

But we should also demo circleci and document the benefits. One benefit
that I see is that it is easier for debugging. In particular, the ability
to run a container with SSH access is incredibly useful when really
clueless about why things fail.

**Comment by lucyleeow** [comment]
> I think that we should demo the github action thing: it is easier to set up.

Is it? ~I'm reading the documentation https://github.com/marketplace/actions/sphinx-build (is this it?) and it leaves a lot to be desired - though I am more of a 'read the documentation' person than 'trial and error'.~ Nevermind, found the documentation, still confusing though.

Regardless putting in a PR for it now
